apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec: 
  tls:
    - hosts:
        - backend.saiexample.art
      secretName: nodejs  
  rules:
  - host: backend.saiexample.art
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: nodejs-service
            port:
              number: 80
