apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: 180169423799.dkr.ecr.us-east-1.amazonaws.com/demo-project:main-0d5257fd486bd5b4a2abb8e9f08947f60e55f656
          ports:
            - containerPort: 8080
